### ISSUE TITLE
Any change of getting an update ?

### ISSUE THREAD

**Issue by layus** [nbp/firefox-build-env#1]
Hi Nicolas,

Is there an updated version of these scripts with support for rust ?

**Comment by nbp** [comment]
Yes, these nix expressions moved to https://github.com/mozilla/nixpkgs-mozilla
I will change the subject of this repository to reflect that.

**Comment by nbp** [comment]
I changed the description.

The nixpkgs-mozilla repository contains a `release.nix` file, which can be used almost the same way, by replacing `build` by `gecko` on the command line.

I already added support for Rust in nixpkgs-mozilla repository, if you have any issue feel free to open an issue on nixpkgs-mozilla and cc me on the issue.

**Comment by layus** [comment]
thanks !
